language: r
sudo: false

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
    - os: linux
      env: RVERSION=3.0.0
    - os: linux
      env: RVERSION=release
    - os: linux
      env: RVERSION=devel
    - os: osx
      env: RVERSION=release
    - os: osx
      env: RVERSION=devel
